{"name": "Ошибка 500 Internal Server Error при попытке сделать заказ авторизованным пользователем с невалидным хешем ингредиента", "status": "broken", "statusDetails": {"message": "NameError: name 'burger_api' is not defined", "trace": "@allure.step(\"Создание пользователя\")\n    @pytest.fixture(scope='function')\n    def default_user():\n>       user_body = burger_api.create_user_body()\nE       NameError: name 'burger_api' is not defined\n\ntests\\conftest.py:8: NameError"}, "description": "При попытке сделать заказ авторизованным пользователем ингредиенты с невалидным хешем, возвращается ошибка 500 Internal Server Error", "start": 1737281554159, "stop": 1737281554159, "uuid": "82c2c451-1b5f-49bb-a588-f7ad8e9004aa", "historyId": "9eeb56360e08e7affc6efa227e1428c6", "testCaseId": "9eeb56360e08e7affc6efa227e1428c6", "fullName": "tests.test_create_order.TestCreateOrder#test_create_order_auth_user_wrong_hash_fail", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_order"}, {"name": "subSuite", "value": "TestCreateOrder"}, {"name": "host", "value": "01ms32"}, {"name": "thread", "value": "15712-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_order"}]}