{"name": "Ошибка 401 при получении списка заказов неавторизованным пользователем", "status": "passed", "description": "Проверка возвращения ошибки 401 Unauthorized при попытке получения cписка заказов неавторизованным пользователем", "steps": [{"name": "Создание заказа", "status": "passed", "parameters": [{"name": "headers", "value": "None"}, {"name": "ingredients", "value": "{'ingredients': ['61c0c5a71d1f82001bdaaa6f', None, '61c0c5a71d1f82001bdaaa6d']}"}], "start": 1737577006517, "stop": 1737577006601}, {"name": "Создание заказа", "status": "passed", "parameters": [{"name": "headers", "value": "None"}, {"name": "ingredients", "value": "{'ingredients': ['61c0c5a71d1f82001bdaaa6f', None, '61c0c5a71d1f82001bdaaa6d']}"}], "start": 1737577006602, "stop": 1737577006673}, {"name": "Получение всех заказов конкретного пользователя", "status": "passed", "parameters": [{"name": "headers", "value": "None"}], "start": 1737577006674, "stop": 1737577006747}], "start": 1737577006517, "stop": 1737577006747, "uuid": "417219a2-db19-4131-b2cb-77c60a2ded4f", "historyId": "6aec763dd17309031b2cb822ff31157d", "testCaseId": "6aec763dd17309031b2cb822ff31157d", "fullName": "tests.test_get_user_orders.TestGetUsersOrders#test_get_order_list_not_auth_user_fail", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_get_user_orders"}, {"name": "subSuite", "value": "TestGetUsersOrders"}, {"name": "host", "value": "01ms32"}, {"name": "thread", "value": "20896-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_get_user_orders"}]}