{"name": "Ошибка 401 Unauthorized при попытке сделать заказ бургера неавторизованным пользователем", "status": "passed", "description": "Неавторизованный пользователь не может сделать заказ бургера, возвращается ошибка 401 Unauthorized", "steps": [{"name": "Создание заказа", "status": "passed", "parameters": [{"name": "headers", "value": "None"}, {"name": "ingredients", "value": "{'ingredients': ['61c0c5a71d1f82001bdaaa6f', None, '61c0c5a71d1f82001bdaaa6d']}"}], "start": 1737282110831, "stop": 1737282110908}], "start": 1737282110830, "stop": 1737282110909, "uuid": "f8b80499-2ba0-4659-9efe-1ac777717392", "historyId": "6d9e4a9cff6b3e758d747c7137a4054e", "testCaseId": "6d9e4a9cff6b3e758d747c7137a4054e", "fullName": "tests.test_create_order.TestCreateOrder#test_create_order_burger_not_auth_user_fail", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_order"}, {"name": "subSuite", "value": "TestCreateOrder"}, {"name": "host", "value": "01ms32"}, {"name": "thread", "value": "4056-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_order"}]}