{"name": "Ошибка 401 при получении списка заказов неавторизованным пользователем", "status": "passed", "description": "Проверка возвращения ошибки 401 Unauthorized при попытке получения cписка заказов неавторизованным пользователем", "steps": [{"name": "Создание заказа", "status": "passed", "parameters": [{"name": "headers", "value": "None"}, {"name": "ingredients", "value": "{'ingredients': ['61c0c5a71d1f82001bdaaa6f', None, '61c0c5a71d1f82001bdaaa6d']}"}], "start": 1737560546306, "stop": 1737560546407}, {"name": "Создание заказа", "status": "passed", "parameters": [{"name": "headers", "value": "None"}, {"name": "ingredients", "value": "{'ingredients': ['61c0c5a71d1f82001bdaaa6f', None, '61c0c5a71d1f82001bdaaa6d']}"}], "start": 1737560546407, "stop": 1737560546571}, {"name": "Получение всех заказов конкретного пользователя", "status": "passed", "parameters": [{"name": "headers", "value": "None"}], "start": 1737560546572, "stop": 1737560546769}], "start": 1737560546305, "stop": 1737560546769, "uuid": "90eae959-6934-4632-a464-13f9bb93767d", "historyId": "6aec763dd17309031b2cb822ff31157d", "testCaseId": "6aec763dd17309031b2cb822ff31157d", "fullName": "tests.test_get_user_orders.TestGetUsersOrders#test_get_order_list_not_auth_user_fail", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_get_user_orders"}, {"name": "subSuite", "value": "TestGetUsersOrders"}, {"name": "host", "value": "01ms32"}, {"name": "thread", "value": "24912-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_get_user_orders"}]}