{"name": "Ошибка 401 при получении списка заказов неавторизованным пользователем", "status": "passed", "description": "Проверка возвращения ошибки 401 Unauthorized при попытке получения cписка заказов неавторизованным пользователем", "steps": [{"name": "Создание заказа", "status": "passed", "parameters": [{"name": "headers", "value": "None"}, {"name": "ingredients", "value": "{'ingredients': ['61c0c5a71d1f82001bdaaa6f', None, '61c0c5a71d1f82001bdaaa6d']}"}], "start": 1737282648420, "stop": 1737282648487}, {"name": "Создание заказа", "status": "passed", "parameters": [{"name": "headers", "value": "None"}, {"name": "ingredients", "value": "{'ingredients': ['61c0c5a71d1f82001bdaaa6f', None, '61c0c5a71d1f82001bdaaa6d']}"}], "start": 1737282648487, "stop": 1737282648560}, {"name": "Получение всех заказов конкретного пользователя", "status": "passed", "parameters": [{"name": "headers", "value": "None"}], "start": 1737282648561, "stop": 1737282648642}], "start": 1737282648420, "stop": 1737282648644, "uuid": "4505f6be-3e2d-423d-9204-af2147803729", "historyId": "6aec763dd17309031b2cb822ff31157d", "testCaseId": "6aec763dd17309031b2cb822ff31157d", "fullName": "tests.test_get_user_orders.TestGetUsersOrders#test_get_order_list_not_auth_user_fail", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_get_user_orders"}, {"name": "subSuite", "value": "TestGetUsersOrders"}, {"name": "host", "value": "01ms32"}, {"name": "thread", "value": "3692-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_get_user_orders"}]}