{"name": "Успешное создание заказа авторизованным пользователем с ингредиентами", "status": "broken", "statusDetails": {"message": "NameError: name 'burger_api' is not defined", "trace": "@allure.step(\"Создание бургера из имеющихся ингредиентов\")\n    @pytest.fixture(scope='function')\n    def default_burger():\n>       ingredients = burger_api.get_ingredients().json()\nE       NameError: name 'burger_api' is not defined\n\ntests\\conftest.py:18: NameError"}, "description": "Авторизация в системе и создание заказа с бургером", "start": 1737281554024, "stop": 1737281554024, "uuid": "b0dfa3e4-1ef2-49b7-9000-38b39bd039a7", "historyId": "47d875b1b9b569c5f71660ce6ba3d594", "testCaseId": "47d875b1b9b569c5f71660ce6ba3d594", "fullName": "tests.test_create_order.TestCreateOrder#test_create_order_burger_auth_user_success", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_order"}, {"name": "subSuite", "value": "TestCreateOrder"}, {"name": "host", "value": "01ms32"}, {"name": "thread", "value": "15712-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_order"}]}